codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "100...100"
  status:
    patch:
      default:
        target: 100%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
