#name: Codecov
#on: [push]
#jobs:
#  run:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        os: [ubuntu-latest]
#        python-version: ["3.10"]
#    env:
#      OS: ${{ matrix.os }}
#      PYTHON: ${{ matrix.python-version }}
#
#    steps:
#    - uses: actions/checkout@master
#    - name: Setup Python
#      uses: actions/setup-python@master
#      with:
#        python-version: ${{ matrix.python-version }}
#    - name: Install Poetry
#      uses: snok/install-poetry@v1
#    - name: Generate coverage report
#      run: |
#        pip install pytest pytest-cov
#        pytest --cov=src/ --cov-report=xml
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v3
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        env_vars: OS,PYTHON
#        fail_ci_if_error: true
#        files: ./coverage.xml
#        flags: unittests
#        verbose: true
