name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Checkout Project Package
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Python Dependencies
      run: poetry install  --no-root -v

    - name: Flake8
      run: poetry run flake8 src/ tests/

    - name: Isort
      run: poetry run isort -c src/ tests/

    - name: Black
      run: poetry run black --check src/ tests/
